name: BTC Lending Backend

services:

  api:
    image: btclendingbackend:latest-${NODE_ENV:-development}
    build:
      context: .
      args:
        - PORT=3000
        - NODE_ENV=development
    env_file: .env
    
    environment:
      - DATABASE_URL=mongodb://mongo:27017/btc-lending
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${PORT:-3000}:${PORT:-3000}"

  mongo:
    image: mongo
    container_name: btc-mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    
  seed:
    image: btclendingbackend:latest-development
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=3000
    command: ["npm", "run", "seed"]
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/btclending

# Using volumes like this stores the data in a Docker-managed location
volumes:
  mongodb-data:
    driver: local
